[[libminc]]
arch = "x86_64"
git-tree-sha1 = "c0eb622bdbd922cc827191456aede8145993fb5f"
libc = "glibc"
os = "linux"

    [[libminc.download]]
    sha256 = "c142925cf3e9dff3580cfbdebd84fefd8d563cc1cc212c5a38d2a9de4a4b56cf"
    url = "https://github.com/JuliaBinaryWrappers/libminc_jll.jl/releases/download/libminc-v2.4.7+0/libminc.v2.4.7.x86_64-linux-gnu.tar.gz"
